import type { Express } from "express";
import { createRateLimiter } from "../middleware/rateLimiter";

export function registerAiRoutes(app: Express) {
  app.post("/api/ai/generate", createRateLimiter({ windowMs: 60 * 1000, max: 5, strict: true, message: "Too many AI generation requests" }), async (req, res) => {
    console.log("🤖 AI Generate request received", { body: req.body });
    try {
      const { prompt, type } = req.body;
      
      if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
        return res.status(400).json({ error: "Prompt is required and must be a non-empty string" });
      }
      if (prompt.length > 5000) {
        return res.status(400).json({ error: "Prompt exceeds maximum length of 5000 characters" });
      }
      
      console.log(`📝 Local simulation of AI generating ${type || 'content'}`);
      
      let mockText = "";
      const lowerPrompt = prompt.toLowerCase();
      if (lowerPrompt.includes("summary") || lowerPrompt.includes("summarize")) {
        mockText = `### AI Summary (Local Database Mode)\n\nThis article provides an in-depth analysis of the latest updates in sports, sourced directly from the Sportivo database. Read the full content below to check user insights, matches stats, and current standings.`;
      } else {
        mockText = `### Draft Article (Local Database Mode)\n\nThis is a premium template generated by Sportivo's database-first environment. You can customize, update, and manage this article directly via your database tables or admin dashboard.`;
      }

      console.log("✅ Local AI Generate successful", { textLength: mockText.length });
      res.json({ text: mockText });
    } catch (error) {
      console.log("❌ AI Generate failed", error);
      res.status(500).json({ error: "Failed to generate AI content" });
    }
  });
}
